# Conexao com o PostgreSQL no AWS RDS
spring.datasource.url=jdbc:postgresql://database-1.cruxqevikxav.us-east-1.rds.amazonaws.com:5432/postgres?sslmode=verify-full&sslrootcert=./global-bundle.pem
spring.datasource.username=postgres
spring.datasource.password=neymar123
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuracoes do Hibernate / JPA para PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Define o schema padrao para todas as tabelas do sistema
spring.jpa.properties.hibernate.default_schema=universidade
# Link para se comunicar com o atlas 
spring.data.mongodb.uri=mongodb+srv://aderekmarques_db_user:derek12345@cluster0.fqszpjv.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=sistema_notas